"""End-to-end integration test for two nodes bootstrapping."""
import time

from peer_discovery.membership.models import ValidationResult
from peer_discovery.network.config import DiscoveryConfig
from peer_discovery.network.discovery_node import DiscoveryNode


def test_two_nodes_bootstrap(tmp_path):
    # 1. Start seed node
    seed_config = DiscoveryConfig(
        advertise_address="seed_node",
        listen_port=0,
        enable_crypto=True,
        key_dir=tmp_path / "seed_keys"
    )
    seed = DiscoveryNode("room-1", seed_config, str(tmp_path / "seed_storage"))
    
    # Optional validator on seed
    def validator(user_id: str, display_name: str, context: dict) -> ValidationResult:
        if display_name == "Banned":
            return ValidationResult(accepted=False, reason="Banned user")
        return ValidationResult(accepted=True)
    seed.service.register_join_validator(validator)
    
    seed.start(display_name="Seed Node")
    
    # Retrieve actual port bound
    seed_host, seed_port = seed.listener.bound_address
    seed_peer = f"{seed_host}:{seed_port}"
    
    try:
        # 2. Start client node connecting to seed
        client_config = DiscoveryConfig(
            advertise_address="client_node",
            listen_port=0,
            enable_crypto=True,
            bootstrap_peers=[seed_peer],
            key_dir=tmp_path / "client_keys"
        )
        client = DiscoveryNode("room-1", client_config, str(tmp_path / "client_storage"))
        
        client.start(display_name="Client Node")
        
        try:
            # Check snapshot on client
            snap = client.service.get_membership_snapshot()
            
            # Should have seed node in snapshot
            assert seed.advertise_address in snap.members
            assert snap.members[seed.advertise_address].display_name == "Seed Node"
            
            # Client's own join request was processed?
            # Wait! The JOIN_ACCEPTED was generated by the seed, but did the seed send it back in the snapshot?
            # Yes, because `handle_join_request` creates the event, THEN gets the snapshot!
            assert client.advertise_address in snap.members
            assert snap.members[client.advertise_address].display_name == "Client Node"
            
        finally:
            client.stop()
            
    finally:
        seed.stop()


def test_bootstrap_rejected(tmp_path):
    # 1. Start seed node
    seed_config = DiscoveryConfig(
        advertise_address="seed_node",
        listen_port=0,
        enable_crypto=True,
        key_dir=tmp_path / "seed_keys2"
    )
    seed = DiscoveryNode("room-1", seed_config, str(tmp_path / "seed_storage2"))
    
    def rejector(user_id: str, display_name: str, context: dict) -> ValidationResult:
        return ValidationResult(accepted=False, reason="Go away")
    seed.service.register_join_validator(rejector)
    
    seed.start(display_name="Seed Node")
    seed_host, seed_port = seed.listener.bound_address
    seed_peer = f"{seed_host}:{seed_port}"
    
    try:
        # 2. Start client node
        client_config = DiscoveryConfig(
            advertise_address="client_node",
            listen_port=0,
            enable_crypto=True,
            bootstrap_peers=[seed_peer],
            key_dir=tmp_path / "client_keys2"
        )
        client = DiscoveryNode("room-1", client_config, str(tmp_path / "client_storage2"))
        
        # Start should fail to join but won't throw exception, just logs warning
        client.start(display_name="Client Node")
        
        try:
            snap = client.service.get_membership_snapshot()
            # Client's snapshot should be empty since it was rejected
            assert len(snap.members) == 0
        finally:
            client.stop()
    finally:
        seed.stop()
